language: rust

script:
  - git clone https://github.com/Microsoft/vcpkg.git
  - cd vcpkg
  - ./bootstrap-vcpkg.sh
  - ./vcpkg integrate install
  - ./vcpkg update
  - ./vcpkg install simpleini
  - cargo build --verbose --workspace
  - cargo test --verbose --workspace