name: Rust

on: [push]

jobs: 
  test_MacOS:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: install_dependencies
      run: | 
        brew install SDL2
        brew install rustup
        rustup-init -y --default-toolchain stable        
    - name: Build
      run: |
        export PATH="$HOME/.cargo/bin:$PATH"
        cargo install cargo-vcpkg
        cargo vcpkg build
        cargo build
    - name: Test
      run: |
        export PATH="$HOME/.cargo/bin:$PATH"
        cargo test

  test_Windows:
    runs-on: windows-2016
    
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: |
        cargo install cargo-vcpkg
        cargo vcpkg build
        cargo build
    - name: Test
      run: cargo test

  test_Linux:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: |
        cargo install cargo-vcpkg
        cargo vcpkg build
        cargo build
    - name: Test
      run: cargo test
